### ISSUE TITLE
Hit reset, game dies

### ISSUE THREAD

**Issue by 12345ieee** [halfburnttoast/Dungeon-Cross#1]
With this trace:
```
Traceback (most recent call last):
  File "/home/andreas/Progetti/bbs/Dungeon-Cross/./dungeon_cross.py", line 852, in <module>
    main()
  File "/home/andreas/Progetti/bbs/Dungeon-Cross/./dungeon_cross.py", line 842, in main
    game.update()
  File "/home/andreas/Progetti/bbs/Dungeon-Cross/./dungeon_cross.py", line 179, in update
    self._menu.mainloop(self._screen, bgfun=self._draw_game)
  File "/home/andreas/.local/lib/python3.10/site-packages/pygame_menu/menu.py", line 2908, in mainloop
    self.update(pygame.event.get())
  File "/home/andreas/.local/lib/python3.10/site-packages/pygame_menu/menu.py", line 2437, in update
    selected_widget.update(events):
  File "/home/andreas/.local/lib/python3.10/site-packages/pygame_menu/widgets/widget/button.py", line 229, in update
    self.apply()
  File "/home/andreas/.local/lib/python3.10/site-packages/pygame_menu/widgets/core/widget.py", line 1258, in apply
    return self._onreturn(*args, **self._kwargs)
  File "/home/andreas/Progetti/bbs/Dungeon-Cross/./dungeon_cross.py", line 628, in _menu_reset
    self.open_puzzle(self.current_puzzle_id())
TypeError: 'int' object is not callable
```

**Comment by halfburnttoast** [comment]
Thanks for the report. I forgot to change the argument from a method call to a property.

I just pushed v1.0.3 which fixes this issue.
